### ISSUE TITLE
Chemical potential, driving force and changing model-parameters

### ISSUE THREAD

**Issue by broshe** [richardotis/pycalphad#18] opened 2015-07-24 07:56 UTC
Hello Richard,
I would like to use pycalphad for a simulation.
Each step requires:
1. calculation of chemical potential and driving forces for phases.
2. changing parameters for the Gibbs energy description of some phases.
3. making equilibrium calculation

Now, for (1), is there a simple means of calculating chemical potential  of a component in phase ? Can you give an example?

For (2) I suspect that the answer could come from the fitting module.  If I include some adjustable parameters in the description of  a phase, changing these parameters may be a way to modify its Gibbs energy. Can this be done in the current version of pycalphad?

Thanks,
Eli Brosh

**Comment by richardotis** [comment] 2015-07-24 13:48
Great to hear from you, Eli. The good news is you will be able to perform your calculations with pycalphad soon, perhaps in the next 10 days.

In the current stable version of pycalphad (0.1.1.post1), there is no way  to calculate chemical potentials. The next version of pycalphad (0.2) will be released very soon, hopefully by the end of the month. The new version features a completely rewritten equilibrium engine and will always return the chemical potentials. You're correct that development is going on in the "fitting" branch, but the new solver is only 90% finished and only returns estimated potentials at the moment.

For (1), the new `equilibrium()` routine will return chemical potentials as the `MU` attribute. For driving force, I haven't yet added it, but you can get the same result by performing a separate `equilibrium()` call with each phase by itself, then computing the difference (weighted sum of chemical potentials minus the energy of the phase by itself at that composition). I will write an example for this with the 0.2 documentation because it's a popular question.

For (2), this is possible by making repeated calls to the `Model` class with the `parameters` keyword argument. Example:
```python
mod = Model(dbf, ['FE', 'C', 'VA'], 'FCC_A1', parameters={'GABCD': 1e4})
```
Then you pass the `model` keyword argument to the `equilibrium()` routine (again, not yet available in the stable version). Example:
```python
mod = Model(dbf, ['FE', 'C', 'VA'], 'FCC_A1', parameters={'GABCD': 1e4})
phases = ['FCC_A1', 'HCP_A3', ...] # other phases here
eq = equilibrium(dbf, ['C', 'FE', 'VA'] , phases, {v.X('C'): (0, 1), v.T: (300, 1400)}, model=[{'FCC_A1': mod}, Model])
```
The `model` argument tells pycalphad to use your special instance of `Model` with the modified parameter for phase `FCC_A1` and to use the defaults from the database for the other phases. You can change the parameter by making another `Model` instance with a different parameter value and calling `equilibrium()` again.

I will send you an e-mail when the new version is released which makes all of this possible.

P.S. By your request, the new version also features progress indicators for the user (issue #16) which can be turned on and off (on by default).

**Comment by broshe** [comment] 2015-07-24 14:01
Thank you very much Richard,
I am looking forward to tho new version.

Best regards,
Eli

**Comment by richardotis** [comment] 2015-08-04 23:13
@broshe, I wanted to give you an update on what is possible in pycalphad now. Check out this example of computing equilibrium carbon activity as a function of pressure: https://github.com/richardotis/pycalphad/blob/3a6fc83e973b527e797b0e4baa69106e2dc21a3e/research/BroshPressureTest.ipynb

At the moment this will only work in the latest `fitting` branch, but I hope to push a stable release soon. There is a performance issue I need to work out with mapping over T, P and composition simultaneously before I'm comfortable releasing, but it otherwise works.

It should also be possible to compute driving force for phases but I don't know of a good example to try. Any suggestions?

It would be great if you could reproduce the same carbon activity calculation in Thermo-Calc to verify that the activities are correct. I don't currently have convenient access to check it.

**Comment by broshe** [comment] 2015-08-05 11:13
Hi Richard,
What is the reference state for the activity calculation?
Eli

**Comment by richardotis** [comment] 2015-08-05 13:33
The reference state is the pure elements in their standard state at 300 K and 1 atm, or whatever is the reference energy you set in your TDB file. I used the default reference state in this case.
On Aug 5, 2015 4:13 AM, broshe <notifications@github.com> wrote:Hi Richard,
What is the reference state for the activity calculation?
Eli

**Comment by broshe** [comment] 2015-08-06 03:06
Hi Richard,
Here is the C activity relative to SER calculated with Thermo-calc:
 Phase Region for:
     FCC_A1
 col-1=P, col-2=AC(C),
   1.00000E+05   2.87082E-04
   2.50098E+08   3.43702E-04
   5.00095E+08   4.11376E-04
   7.50092E+08   4.92240E-04
   1.00009E+09   5.88842E-04
   1.25009E+09   7.04217E-04
   1.50008E+09   8.41978E-04
   1.75008E+09   1.00643E-03
   2.00008E+09   1.20270E-03
   2.25008E+09   1.43688E-03
   2.50008E+09   1.71624E-03
   2.75007E+09   2.04941E-03
   3.00007E+09   2.44668E-03
   3.25007E+09   2.92025E-03
   3.50006E+09   3.48467E-03
   3.75006E+09   4.15723E-03
   4.00006E+09   4.95845E-03
   4.25006E+09   5.91275E-03
   4.50006E+09   7.04914E-03
   4.75005E+09   8.40209E-03
   5.00005E+09   1.00125E-02
   5.25005E+09   1.19290E-02
   5.50004E+09   1.42094E-02
   5.75004E+09   1.69221E-02
   6.00004E+09   2.01484E-02
   6.25004E+09   2.39849E-02
   6.50004E+09   2.85461E-02
   6.75003E+09   3.39678E-02
   7.00003E+09   4.04112E-02
   7.25003E+09   4.80674E-02
   7.50002E+09   5.71628E-02
   7.75002E+09   6.79661E-02
   8.00002E+09   8.07956E-02
   8.25002E+09   9.60286E-02
   8.50002E+09   1.14112E-01
   8.75001E+09   1.35576E-01
   9.00001E+09   1.61047E-01
   9.25001E+09   1.91268E-01
   9.50000E+09   2.27120E-01
   9.75000E+09   2.69643E-01
   1.00000E+10   3.20071E-01



​
Best regards,
Eli

**Comment by richardotis** [comment] 2015-08-24 15:54
0.2 has been released, so the concerns in this issue should be addressed.

**Closed by richardotis** 2015-08-24 15:54 UTC
